modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/SmiteMCde/Menu-Hotkey/issues"
license = "All Rights Reserved"

[[mods]]
modId = "smitemc_hotkey"
version = "${version}"
displayName = "SmiteMC Menu Hotkey"
authors = "LeonJS_"
description = '''
Adds a shortcut (hotkey) for opening the main menu for the Minecraft Earth game mode on the SmiteMC Network.
'''
#logoFile = ""

[[dependencies.smitemc_hotkey]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smitemc_hotkey]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smitemc_hotkey]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "smitemc_hotkey.mixins.json"
